# docker-compose for HTTP/2 slowloris part B  
name: http2-slowloris-lab-B

services:
  victim:
    build:
      context: .
      dockerfile: Dockerfile.victim
    container_name: loris-victim-apache-latest
    ports:
      - "8080:80" # HTTP/2 cleartext
    networks:
      - attack-net

  attacker:
    build:
      context: .
      dockerfile: Dockerfile.advanced_slowloris_attacker
    container_name: http2-adv-slowloris-attacker
    environment:
      - PYTHONUNBUFFERED=1
    # Advanced HTTP/2 Slowloris attack with adaptive streams and stealth features
    command: >
      python advanced_slowloris.py 
      victim 
      300 
      --streams 15 
      --sleep 12
    networks:
      - attack-net
    depends_on:
      - victim

networks:
  attack-net: