# http_flood_lab/docker-compose.part_B.yml
name: http_flood-lab-b

services:
  victim:
    build:
      context: ..
      dockerfile: part_B/Dockerfile.victim_multi 
    container_name: prod-victim-server
    ports:
      - "8080:80"
    networks:
      - attack-net
    environment:
    # the higher the number - the busiest the server to handle one response
      - DIFFICULITY=5
    command: gunicorn --workers 4 --bind 0.0.0.0:80 victim_app:app # multi-threaded Gunicorn server with configurable number of workers (depends on the cores of the cpu)
    
  
  attacker:
    build:
      context: ..
      dockerfile: Dockerfile.flood_attcker
    container_name: flood-attacker-client-B
    environment:
      - PYTHONUNBUFFERED=1
    command: python http_flood.py http://victim 128
    networks:
      - attack-net
    depends_on:
      - victim

networks:
  attack-net: