# docker-compose for slowloris part A - HTTP/1.1
name: slowloris-lab-A
services:
  victim:
    image: httpd:2.2.14  # Old Apache server
    container_name: loris-victim-server
    ports:
      - "8080:80"
    networks:
      - attack-net

  attacker:
    build:
      context: .
      dockerfile: Dockerfile.slowloris_attacker
    container_name: loris-attacker-client
    environment:
      - PYTHONUNBUFFERED=1
    command: python slowloris.py victim 256
    networks:
      - attack-net
    depends_on:
      - victim

networks:
  attack-net: