version: "3.3"

services:
  victim:
    image: httpd:2.2
    container_name: loris-victim-server
    ports:
      - "8080:80"
    networks:
      - attack-net

  attacker:
    build:
      context: .
      dockerfile: Dockerfile.slowloris_attacker
    container_name: loris-attacker-client
    environment:
      PYTHONUNBUFFERED: "1"
    command: ["python", "slowloris_attack.py", "victim", "256"]
    depends_on:
      - victim
    networks:
      - attack-net

networks:
  attack-net:
